name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Install go beta
      run: |
        go install golang.org/dl/go1.18beta2@latest
        go1.18beta2 download
        cp $(which go1.18beta2) $(which go)
        go version

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
